######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 19 20:03:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += func.h MainWindow.h pages.h
SOURCES += func.cpp main.cpp MainWindow.cpp pages.cpp
