######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 19 13:30:57 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
CONFIG += qt debug
HEADERS += func.h MainWindow.h pages.h
SOURCES += func.cpp main.cpp MainWindow.cpp pages.cpp
